// Generated by CoffeeScript 1.4.0
(function() {
  var createFlake, delay, flakes, i, main, moveFlakes, win, winHeight, winWidth, _i;

  main = $('#main');

  win = $(window);

  winWidth = win.width();

  winHeight = win.height();

  delay = 0;

  flakes = [];

  createFlake = function() {
    var flake;
    flake = $('<div class="snowflake" data-size="' + Math.floor(Math.random() * 4) + '">*</div>');
    flake.css({
      position: 'absolute',
      top: Math.floor(Math.random() * winHeight),
      left: Math.floor(Math.random() * winWidth),
      opacity: 0
    });
    main.append(flake);
    delay += 100;
    setTimeout((function() {
      return flake.css('opacity', 0.5);
    }), delay);
    return flake;
  };

  for (i = _i = 0; _i <= 30; i = ++_i) {
    flakes.push(createFlake());
  }

  moveFlakes = function() {
    $.each(flakes, function() {
      var flake, newTop, pos;
      flake = this;
      pos = flake.position();
      newTop = pos.top < winHeight ? pos.top + 1 : 0;
      if (newTop !== 0) {
        return flake.css({
          top: newTop
        });
      } else {
        flake.css({
          top: newTop,
          opacity: 0
        });
        return setTimeout((function() {
          return flake.css('opacity', 0.5);
        }), 250);
      }
    });
    return setTimeout(moveFlakes, 100);
  };

  moveFlakes();

}).call(this);
